# This analysis_options.yaml is needed so that the Dart analyzer doesn't use the parent directory's analysis_options.yaml,
# which excludes this example directory.

# analysis_options.yaml docs: https://www.dartlang.org/guides/language/analysis-options
analyzer:
  # Strong mode is required. Applies to the current project.
  strong-mode:
    # When compiling to JS, both implicit options apply to the current 
    # project and all dependencies. They are useful to find possible 
    # Type fixes or areas for explicit typing.
    implicit-casts: false
    implicit-dynamic: true
