version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pub"
    directories:
      - "/"
      - "/example"
      - "/w_flux_codemod"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 4
