language: dart
dart:
  - 2.4.1
  - stable
  - dev
sudo: required
addons:
  chrome: stable
# Re-use downloaded pub packages everywhere.
cache:
  directories:
    - $HOME/.pub-cache
jobs:
  include:
    - dart: 2.4.1
      name: "SDK: 2.4.1"
      script:
        - pub run dart_dev analyze
        - pub run dart_dev test
    - dart: stable
      name: "SDK: stable"
      script:
        - pub run dart_dev format --check
        - pub run dart_dev analyze
        - pub run dart_dev test
    - dart: dev
      name: "SDK: dev"
      script:
        - pub run dart_dev analyze
        - pub run dart_dev test
