language: dart
dart:
  - stable
sudo: required
addons:
  chrome: stable
# Re-use downloaded pub packages everywhere.
cache:
  directories:
    - $HOME/.pub-cache
dart_task:
  - test: --platform vm
  - test: --platform chrome
  - dartfmt: true
  - dartanalyzer: example lib test tool
