language: dart

sudo: required
addons:
  chrome: stable

# Re-use downloaded pub packages everywhere.
cache:
  directories:
    - $HOME/.pub-cache

jobs:
  include:
    - dart: stable
      name: "SDK: stable"
      script:
        - pub run dart_dev format --check
        - pub run dart_dev analyze
        - pub run dart_dev test --release
    - dart: dev
      name: "SDK: dev"
      script:
        - pub run dart_dev analyze
        - pub run dart_dev test --release
