language: dart
dart:
  - 1.24.3
  - stable
sudo: required
addons:
  chrome: stable
dart_task:
  - test: --platform vm
  - test: --platform chrome
  - dartfmt: true
  - dartanalyzer: example lib test tool
