include: package:workiva_analysis_options/v2.yaml
# analysis_options.yaml docs: https://www.dartlang.org/guides/language/analysis-options
analyzer:
  exclude:
    - "example/**"
    - "w_flux_codemod/**"
  language:
    strict-casts: true
