name: w_flux_codemod
version: 1.0.0
description: codemod for migrating to ActionV2
homepage: https://github.com/Workiva/w_flux/w_flux_codemod

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ^5.13.0
  codemod: ^1.1.0
  glob: ^2.1.2
  workiva_analysis_options: ^1.3.0

executables:
  action_v2_migrate:
