name: w_flux_codemod
version: 1.0.0
description: codemod for migrating to ActionV2
homepage: https://github.com/Workiva/w_flux/tree/master/w_flux_codemod

environment:
  sdk: ">=2.19.0 <3.0.0"

executables:
  action_v2_migrate:
  action_v2_migrate_step_1:
  action_v2_migrate_step_2:

dependencies:
  analyzer: ^5.13.0
  codemod: ^1.1.0
  glob: ^2.1.2
  workiva_analysis_options: ^1.3.0

dev_dependencies:
  meta: ^1.11.0
  source_span: ^1.10.0
  test: ^1.24.3
