name: CI

on:
  push:
    branches:
      - 'master'
      - 'test_consume_*'
    tags:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  dart:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk: [ 2.19.6, stable ]
    name: Dart ${{ matrix.sdk }}
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - name: Install dependencies
        run: dart pub get
      - name: Validate dependencies
        run: dart run dependency_validator
      - name: Analysis
        run: dart analyze
      - name: Formatting
        run: dart format --set-exit-if-changed .
        if: ${{ matrix.sdk == 'stable' }}
      - name: Tests
        run: dart run dart_dev test
      - name: Tests (dart2js)
        run: dart run dart_dev test --release
      - name: SBOM
        if: ${{ matrix.sdk == 'stable' }}
        uses: anchore/sbom-action@v0
        with:
          path: ./
          format: cyclonedx-json
